### PR TITLE
[BUG] Lower case with default separator

### LINKED ISSUE #2478: How to index JSON Array
Am trying to create my index on a array of json but it dosen't seem to work any way.
this is my index => 

```javascript
await redisClient.ft.create(`${indexName}:tt`, {
            '$.attributes[*].value': {
                type: SchemaFieldTypes.TEXT,
                AS: 'attributes'
            },
        }, {
            ON: 'JSON',
            PREFIX: 'mobiles:'
        });
```

I also tried => 

```javascript
await redisClient.ft.create(`${indexName}:tt`, {
            '$.attributes[0:].value': {
                type: SchemaFieldTypes.TEXT,
                AS: 'attributes'
            },
        }, {
            ON: 'JSON',
            PREFIX: 'mobiles:'
        });
```

but this also didn't work.

my array of json => 

```javascript
  attributes: [
    { name: 'Brand', value: 'Vivo' },
    { name: 'Color', value: 'Mirror Black' },
    { name: 'Sim Type', value: 'Dual Sim' }
]
```

### PR DESCRIPTION
**Pull request by ashtul**
fixes #2478

### CODE REVIEW

File: src/tag_index.c [hunk 1]
```diff
@@ -59,7 +59,7 @@ char *TagIndex_SepString(char sep, char **s, size_t *toklen) {
 
 static int tokenizeTagString(const char *str, char sep, TagFieldFlags flags, char ***resArray) {
   if (sep == TAG_FIELD_DEFAULT_JSON_SEP) {
-    *resArray = array_append(*resArray, rm_strdup(str));
+    *resArray = array_append(*resArray, strtolower(rm_strdup(str)));
```
Comment (oshadmi) [inline src/tag_index.c:62]: Shouldn't we also consider `flags & TagField_CaseSensitive` as with none-default separator?
(can also use `tag_strtolower` function?)

Comment (ashtul) [reply src/tag_index.c]: good call. 
Fixed and tests added.

**Review by oshadmi — APPROVED** [review]
👍🏼
