### PR TITLE
fix inverted_sz_mb and num_records value for ft.info

### LINKED ISSUE #1184: ft.info returns incorrect `inverted_sz_mb`
```
19) inverted_sz_mb
20) "4.6470164452076421e+18"
```

### PR DESCRIPTION
**Pull request by ashtul**
fix #1184
values were not increased at addition for both `GEO` and `NUMERIC` and were decreased for `NUMERIC` in GC. The reduction of `size_t` value caused an overflow.

### CODE REVIEW

**Comment by ashtul** [comment]
`#define GEO_STORAGE_SIZE 48` is a place holder for real consumption of GEO in redis

File: src/document.c [hunk 1]
```diff
@@ -472,6 +474,8 @@ FIELD_BULK_INDEXER(geoIndexer) {
     QueryError_SetError(status, QUERY_EGENERIC, "Could not index geo value");
     return -1;
   }
+  ctx->spec->stats.invertedSize += GEO_STORAGE_SIZE; // TODO: exact amount
+  ctx->spec->stats.numRecords++;
```
Comment (MeirShpilraien) [inline src/document.c:478]: Maybe we should not count the geo because it's not really an inverted index that we keep and redis counts it in its global memory report?

Comment (ashtul) [reply src/document.c:478]: @gkorland @mnunberg 
Should we count GEO here?

> Why not just update the stats on InvertedIndex_WriteEntryGeneric instead of returning the size all the way back?

The stats are recorded on the spec which isn't available there.

**Comment by ashtul** [comment]
> Why not just update the stats on InvertedIndex_WriteEntryGeneric instead of returning the size all the way back?

The stats are recorded on the spec which isn't available there.

**Comment by MeirShpilraien** [comment]
- [ ] Cherry-pick to 1.6
- [ ] Add a PR on the coordinator to make sure it's not breaking it

File: src/numeric_index.h [hunk 2]
```diff
@@ -52,6 +52,11 @@ typedef struct rtNode {
   NumericRange *range;
 } NumericRangeNode;
 
+typedef struct {
+  size_t sz;
```
Comment (mnunberg) [inline src/numeric_index.h:56]: This probably should be reduced in order to fit into 8 bytes; let's make the stack work less!
