### PR TITLE
fixed case issue MOD-4872

### LINKED ISSUE #3391: Wildcards don't work on case sensitive tags
Version information
```
Redis version found by RedisSearch : 6.2.8 - oss
RediSearch version 2.6.4 (Git=HEAD-9fcb4429)
```
Steps to reproduce
```
FT.CREATE idx1 SCHEMA  field1 TAG CASESENSITIVE WITHSUFFIXTRIE
HSET r5 field1 TEST4
FT.SEARCH idx1 "@field1:{TEST*}"
1) (integer) 0
```
However without the `CASESENSITIVE` option : 
```
FT.CREATE idx2 SCHEMA  field1 TAG WITHSUFFIXTRIE
HSET r5 field1 TEST4
FT.SEARCH idx2 "@field1:{TEST*}"
1) (integer) 1
2) "r5"
3) 1) "field1"
   2) "TEST4"
```
Results found

### PR DESCRIPTION
**Pull request by DvirDukhan**
This PR removes redunant "to lower" transformation for prefix nodes and introduces `rm_strndupescape` to duplicate and escape strings.
The prefix string will be modify to lower case when in
1. tag - `query_EvalSingleTagNode` calls to `tag_strtolower` when tag field is case sensitive
2. text - `Query_EvalPrefixNode` calls `strToFoldedRunes` which transform the query string into lower case regardless

added test
closes MOD-4872, closes #3391

### CODE REVIEW

**Review by rafie — APPROVED** [review]

**Review by rafie — DISMISSED** [review]

File: src/query.c [hunk 1]
```diff
@@ -213,7 +213,7 @@ QueryNode *NewPrefixNode_WithParams(QueryParseCtx *q, QueryToken *qt, bool prefi
   ret->pfx.suffix = suffix;
   q->numTokens++;
   if (qt->type == QT_TERM) {
-    char *s = rm_strdupcase(qt->s, qt->len);
+    char *s = rm_strndup_unescape(qt->s, qt->len);
```
Comment (oshadmi) [inline src/query.c:216]: Need to also handle `PARAMS`, such as [this test](https://github.com/RediSearch/RediSearch/blob/ead2df092ba6ba002e61b8a5e505e18e94968c23/tests/pytests/test_contains.py#L356)

(`QT_TERM_CASE` and `QT_PARAM_TERM_CASE` ?)

File: src/query.c [hunk 2]
```diff
@@ -1539,10 +1539,15 @@ void QueryNode_SetFieldMask(QueryNode *n, t_fieldMask mask) {
...
-          children[ii]->type == QN_PREFIX || children[ii]->type == QN_LEXRANGE ||
-          children[ii]->type == QN_WILDCARD_QUERY) {
+      QueryNode *child = children[ii];
+      if (child->type == QN_TOKEN || child->type == QN_PHRASE ||
+          child->type == QN_PREFIX || child->type == QN_LEXRANGE ||
+          child->type == QN_WILDCARD_QUERY) {
         n->children = array_ensure_append(n->children, children + ii, 1, QueryNode *);
+        for(size_t jj = 0; jj < QueryNode_NumParams(child); ++jj) {
+          Param *p = child->params + jj;
+          p->type = PARAM_TERM_CASE;
```
Comment (oshadmi) [inline src/query.c:1549]: When evaluating `PARAM_TERM_CASE`  we use `rm_strdup` and not `rm_strndup_unescape` 
https://github.com/RediSearch/RediSearch/blob/7eae2f60a71bf5122e369faa3ce0e8baa5a94e6c/src/query_param.c#L176
So we do not unescape params?

**Review by oshadmi — APPROVED** [review]
Let's handle [un-escaping params](https://github.com/RediSearch/RediSearch/pull/3403/files#r1115307827) in another PR

**Review by oshadmi — APPROVED** [review]
