### PR TITLE
[BUG]  remove limit on geo percision

### LINKED ISSUE #2390: Indexing errors on very precise geo-coordinates
Valid, but very precise geocoordinates raise a silent error when being indexed, for example, take 25.5436204488196,28.03175610792122 (a random, very precise geoloc)

```text
127.0.0.1:6379> FT.CREATE test on HASH prefix 1 test: schema loc geo
OK
127.0.0.1:6379> HSET test:1 loc 25.5436204488196,28.03175610792122
(integer) 1
127.0.0.1:6379> FT.SEARCH test *
1) (integer) 0
```text

does not index correctly, while the same coordinates plugged into a geodata structure will index just fine:

```
127.0.0.1:6379> GEOADD testgeo 25.5436204488196 28.03175610792122 foo
(integer) 1
127.0.0.1:6379> GEOADD testgeo 23 24 bar
(integer) 1
127.0.0.1:6379> GEODIST testgeo foo bar
"515452.4725"
```

meanwhile, in the index, you can spot the failure:

```text
127.0.0.1:6379> FT.INFO test
 1) index_name
 2) test
 3) index_options
 4) (empty array)
 5) index_definition
 6) 1) key_type
    2) HASH
    3) prefixes
    4) 1) test:
    5) default_score
    6) "1"
 7) fields
 8) 1) 1) loc
       2) type
       3) GEO
 9) num_docs
10) "0"
11) max_doc_id
12) "0"
13) num_terms
14) "0"
15) num_records
16) "0"
17) inverted_sz_mb
18) "0"
19) total_inverted_index_blocks
20) "0"
21) offset_vectors_sz_mb
22) "0"
23) doc_table_size_mb
24) "0"
25) sortable_values_size_mb
26) "0"
27) key_table_size_mb
28) "1.239776611328125e-05"
29) records_per_doc_avg
30) "-nan"
31) bytes_per_record_avg
32) "-nan"
33) offsets_per_term_avg
34) "-nan"
35) offset_bits_per_record_avg
36) "-nan"
37) hash_indexing_failures
38) "1"
39) indexing
40) "0"
41) percent_indexed
42) "1"
43) gc_stats
44)  1) bytes_collected
     2) "0"
     3) total_ms_run
     4) "0"
     5) total_cycles
     6) "0"
     7) average_cycle_time_ms
     8) "-nan"
     9) last_run_time_ms
    10) "0"
    11) gc_numeric_trees_missed
    12) "0"
    13) gc_blocks_denied
    14) "0"
45) cursor_stats
46) 1) global_idle
    2) (integer) 0
    3) global_total
    4) (integer) 0
    5) index_capacity
    6) (integer) 128
    7) index_total
    8) (integer) 0
```

I think this failure is most likely due to this [line](https://github.com/RediSearch/RediSearch/blob/096f7cc7557c27cd6a0352a954cb75041d7c38a9/src/rs_geo.c#L102) - which checks if the geostring is greater than 31 characters in length (the provided string is 34). I'm guessing is meant as a shorthand to check to see if the numbers in the geoloc are valid doubles, and probably for some exponents, they are.

Obviously pretty minor, these are very precise coordinates that I don't think there are many practical applications for.

### PR DESCRIPTION
**Pull request by ashtul**
fixes #2390

### CODE REVIEW

File: src/rs_geo.c [hunk 1]
```diff
@@ -99,10 +99,6 @@ bool isWithinRadiusLonLat(double lon1, double lat1, double lon2, double lat2, do
 }
 
 int parseGeo(const char *c, size_t len, double *lon, double *lat) {
-  if (len > 31) {
-    return REDISMODULE_ERR;
-  }
-
   char str[len + 1];
```
Comment (oshadmi) [inline src/rs_geo.c:102]: Should we still keep some protection, e.g., against stack overflow on ridiculously long input?

Comment (ashtul) [reply src/rs_geo.c:102]: redis has a limit of 512MB

**Review by oshadmi — APPROVED** [review]
👍🏼
