### PR TITLE
Count failed  indexing of HSET

### LINKED ISSUE #1451: Add field to FT.INFO with number of errors on indexing documents not matching schema
+ log the error

### PR DESCRIPTION
**Pull request by ashtul**
fix #1451

### CODE REVIEW

File: src/document.h [hunk 1]
```diff
@@ -250,6 +250,7 @@ typedef struct RSAddDocumentCtx {
   uint32_t specFlags;    // Cached index flags
   uint8_t options;       // Indexing options - i.e. DOCUMENT_ADD_xxx
   uint8_t stateFlags;    // Indexing state, ACTX_F_xxx
+  IndexStats *stats;
```
Comment (rafie) [inline src/document.h:253]: No ownership issues here?

File: src/spec.h [hunk 2]
```diff
@@ -114,6 +114,7 @@ typedef struct {
   size_t offsetVecsSize;
   size_t offsetVecRecords;
   size_t termsSize;
+  size_t indexFailures;
```
Comment (rafie) [inline src/spec.h:117]: `indexingFailures`?

File: src/document.c [hunk 3]
```diff
@@ -573,6 +574,7 @@ int Document_AddToIndexes(RSAddDocumentCtx *aCtx) {
 
       PreprocessorFunc pp = preprocessorMap[ii];
       if (pp(aCtx, &doc->fields[i], fs, fdata, &aCtx->status) != 0) {
+        ++aCtx->stats->indexFailures;
```
Comment (MeirShpilraien) [inline src/document.c:577]: This is not safe when running in concurrent write mode, We need to see if we blocked and if we did we need to take the GIL before do it (and make sure the index still exists).

File: docs/Commands.md [hunk 4]
```diff
@@ -170,6 +170,22 @@ OK or an error
...
+
+```
+HSET {hash} {field} {value} [{field} {value} ...]
+```
+
+### Description
+
+Since RediSearch v2.0, native redis commands are used to add, update and delete hashes.
+RediSearch `2.0` treats the hash in the same manner a document was treated in `1.x`.
+If a field fails to be indexed, the whole document is not indexed. The number of field which failed to index is in `FT.INFO`.
```
Comment (MeirShpilraien) [inline docs/Commands.md:185]: Isn't it the number of times a failure happened?

File: src/document.c [hunk 5]
```diff
@@ -573,6 +575,15 @@ int Document_AddToIndexes(RSAddDocumentCtx *aCtx) {
 
       PreprocessorFunc pp = preprocessorMap[ii];
       if (pp(aCtx, &doc->fields[i], fs, fdata, &aCtx->status) != 0) {
+        if (!AddDocumentCtx_IsBlockable(aCtx)) {
+          ++aCtx->spec->stats.indexingFailures;
+        } else {
+          RedisModule_ThreadSafeContextLock(RSDummyContext);
+          if (aCtx->spec->uniqueId == aCtx->specId) {
```
Comment (MeirShpilraien) [inline src/document.c:582]: @ashtul the idea with checking the unique id is to prevent accessing spec which was free. So you can not really access the aCtx->spec without verifying the spec pointer is valid. you need to reopen the spec (using the spec name) and then compare the ids (or if you failed to open you know the spec was deleted).

Comment (ashtul) [reply src/document.c]: Done

File: src/document.c [hunk 6]
```diff
@@ -573,6 +579,16 @@ int Document_AddToIndexes(RSAddDocumentCtx *aCtx) {
 
       PreprocessorFunc pp = preprocessorMap[ii];
       if (pp(aCtx, &doc->fields[i], fs, fdata, &aCtx->status) != 0) {
+        if (!AddDocumentCtx_IsBlockable(aCtx)) {
+          ++aCtx->spec->stats.indexingFailures;
+        } else {
+          RedisModule_ThreadSafeContextLock(RSDummyContext);
+          IndexSpec *spec = dictFetchValue(specDict_g, aCtx->specName);
```
Comment (MeirShpilraien) [inline src/document.c:586]: I think we have a function to open an inverted index by name no?

File: src/document.c [hunk 7]
```diff
@@ -175,6 +175,11 @@ RSAddDocumentCtx *NewAddDocumentCtx(IndexSpec *sp, Document *b, QueryError *stat
   aCtx->next = NULL;
   aCtx->specFlags = sp->flags;
   aCtx->indexer = sp->indexer;
+  aCtx->spec = sp;
+  if (aCtx->specFlags & Index_Async) {
+    aCtx->specName = rm_strdup(sp->name);
```
Comment (MeirShpilraien) [inline src/document.c:180]: aCtx is allocated from a pool so it might be a good idea to reuse the memory here (allocate once and reallocate if a larger name arrives), what do you think?

**Review by MeirShpilraien — COMMENTED** [review]
Small comments, let me know what you think. Also, any reason you change specDict to specDict_g?

**Comment by ashtul** [comment]
> Small comments, let me know what you think. Also, any reason you change specDict to specDict_g?

Yes. We now have global variables such as actxPool_g, functions_g, ScemaPrefixes_g, SchemaRules_g, gcThreadpool_g. It makes it slightly clearer.

**Review by MeirShpilraien — APPROVED** [review]
