### PR TITLE
Fix #3230, use the correct max results value.

### LINKED ISSUE #3230: Precalculated number of replies must be equal to actual number
I'm running into an issue when looping through an index with more than 10k entries. I have increased the MAXSEARCHRESULTS settings to 1M up from the default of 10k. When I get to the 10k'th result, with a limit of 100, redis crashes and I get the stack trace below.

System info:
```
Os: Windows Server 2019 Datacenter 
Version: 1809
CPU: Intel Xeon E5
```

Search:
```
argv[0]: 'FT.SEARCH'
argv[1]: 'Security:index'
argv[2]: '*'
argv[3]: 'LIMIT'
argv[4]: '10000'
argv[5]: '100'
argv[6]: 'RETURN'
argv[7]: '0'
```

I left the last line from above the stack trace in there because I think it might be relevant:

```
9:M 16 Nov 2022 18:48:58.713 # <search> Precalculated number of replies must be equal to actual number


=== REDIS BUG REPORT START: Cut & paste starting from here ===
9:M 16 Nov 2022 18:48:58.713 # === ASSERTION FAILED ===
9:M 16 Nov 2022 18:48:58.713 # ==> /build/src/aggregate/aggregate_exec.c:305 'resultsLen == nelem' is not true

------ STACK TRACE ------

Backtrace:
/opt/redis-stack/lib/redisearch.so(sendChunk+0x50f)[0x7f6ee00a49ef]
/opt/redis-stack/lib/redisearch.so(AREQ_Execute+0x1d)[0x7f6ee00a4cad]
/opt/redis-stack/lib/redisearch.so(+0xfeefc)[0x7f6ee00a4efc]
/opt/redis-stack/bin/redis-server *:6379(RedisModuleCommandDispatcher+0x67)[0x557c727f5f67]
/opt/redis-stack/bin/redis-server *:6379(call+0xf0)[0x557c72767860]
/opt/redis-stack/bin/redis-server *:6379(processCommand+0x643)[0x557c72769593]
/opt/redis-stack/bin/redis-server *:6379(processCommandAndResetClient+0x20)[0x557c7277cb40]
/opt/redis-stack/bin/redis-server *:6379(processInputBuffer+0xea)[0x557c7277f49a]
/opt/redis-stack/bin/redis-server *:6379(+0x10119c)[0x557c7281819c]
/opt/redis-stack/bin/redis-server *:6379(aeProcessEvents+0x2ca)[0x557c7275fe2a]
/opt/redis-stack/bin/redis-server *:6379(aeMain+0x1d)[0x557c727600bd]
/opt/redis-stack/bin/redis-server *:6379(main+0x33a)[0x557c7275c4ca]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f6ee0d0e083]
/opt/redis-stack/bin/redis-server *:6379(_start+0x2e)[0x557c7275c9ce]

------ INFO OUTPUT ------
# Server
redis_version:6.2.7
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:adcdff4a0d295794
redis_mode:standalone
os:Linux 5.10.104-linuxkit x86_64
arch_bits:64
monotonic_clock:POSIX clock_gettime
multiplexing_api:epoll
atomicvar_api:c11-builtin
gcc_version:9.4.0
process_id:9
process_supervised:no
run_id:986fb66bbff7d16c56fb4f80efedcc20358a9e7d
tcp_port:6379
server_time_usec:1668624538699073
uptime_in_seconds:352
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:7680154
executable:/opt/redis-stack/bin/redis-server
config_file:
io_threads_active:0

# Clients
connected_clients:6
cluster_connections:0
maxclients:10000
client_recent_max_input_buffer:114764
client_recent_max_output_buffer:0
blocked_clients:0
tracking_clients:0
clients_in_timeout_table:0

# Memory
used_memory:530173400
used_memory_human:505.61M
used_memory_rss:556298240
used_memory_rss_human:530.53M
used_memory_peak:530914024
used_memory_peak_human:506.32M
used_memory_peak_perc:99.86%
used_memory_overhead:5062664
used_memory_startup:1006344
used_memory_dataset:525110736
used_memory_dataset_perc:99.23%
allocator_allocated:530299672
allocator_active:532398080
allocator_resident:543924224
total_system_memory:2047266816
total_system_memory_human:1.91G
used_memory_lua:32768
used_memory_lua_human:32.00K
used_memory_scripts:0
used_memory_scripts_human:0B
number_of_cached_scripts:0
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:1.00
allocator_frag_bytes:2098408
allocator_rss_ratio:1.02
allocator_rss_bytes:11526144
rss_overhead_ratio:1.02
rss_overhead_bytes:12374016
mem_fragmentation_ratio:1.05
mem_fragmentation_bytes:26206368
mem_not_counted_for_evict:0
mem_replication_backlog:0
mem_clients_slaves:0
mem_clients_normal:172192
mem_aof_buffer:0
mem_allocator:jemalloc-5.1.0
active_defrag_running:0
lazyfree_pending_objects:0
lazyfreed_objects:0

# Persistence
loading:0
current_cow_size:0
current_cow_size_age:0
current_fork_perc:0.00
current_save_keys_processed:0
current_save_keys_total:0
rdb_changes_since_last_save:2702
rdb_bgsave_in_progress:0
rdb_last_save_time:1668624516
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:29
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:39485440
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0
module_fork_in_progress:0
module_fork_last_cow_size:0

# Stats
total_connections_received:9
total_commands_processed:32118
instantaneous_ops_per_sec:136
total_net_input_bytes:49022392
total_net_output_bytes:77241024
instantaneous_input_kbps:539.17
instantaneous_output_kbps:188.98
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
expire_cycle_cpu_milliseconds:5
evicted_keys:0
keyspace_hits:314920
keyspace_misses:0
pubsub_channels:1
pubsub_patterns:0
latest_fork_usec:11225
total_forks:5
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0
tracking_total_keys:0
tracking_total_items:0
tracking_total_prefixes:0
unexpected_error_replies:0
total_error_replies:1
dump_payload_sanitizations:0
total_reads_processed:13177
total_writes_processed:11580
io_threaded_reads_processed:0
io_threaded_writes_processed:0

# Replication
role:master
connected_slaves:0
master_failover_state:no-failover
master_replid:c7fdb1591f3996a684d015bd76dd67124591ea65
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:2.602724
used_cpu_user:15.190707
used_cpu_sys_children:1.592204
used_cpu_user_children:4.305288
used_cpu_sys_main_thread:2.450667
used_cpu_user_main_thread:15.011667

# Modules
module:name=graph,ver=20820,api=1,filters=0,usedby=[],using=[ReJSON],options=[]
module:name=search,ver=20415,api=1,filters=0,usedby=[],using=[ReJSON],options=[handle-io-errors]
module:name=ReJSON,ver=20200,api=1,filters=0,usedby=[search|graph],using=[],options=[handle-io-errors]
module:name=timeseries,ver=10617,api=1,filters=0,usedby=[],using=[],options=[handle-io-errors]
module:name=bf,ver=20218,api=1,filters=0,usedby=[],using=[],options=[]

# Commandstats
cmdstat_client:calls=3,usec=7,usec_per_call=2.33,rejected_calls=0,failed_calls=0
cmdstat_json.objkeys:calls=2,usec=279,usec_per_call=139.50,rejected_calls=0,failed_calls=0
cmdstat_type:calls=505,usec=492,usec_per_call=0.97,rejected_calls=0,failed_calls=0
cmdstat_subscribe:calls=14,usec=61,usec_per_call=4.36,rejected_calls=0,failed_calls=0
cmdstat_FT.SEARCH:calls=204,usec=2351548,usec_per_call=11527.20,rejected_calls=0,failed_calls=1
cmdstat_memory:calls=505,usec=3554,usec_per_call=7.04,rejected_calls=0,failed_calls=0
cmdstat_json.debug:calls=5,usec=213,usec_per_call=42.60,rejected_calls=0,failed_calls=0
cmdstat_info:calls=20,usec=2799,usec_per_call=139.95,rejected_calls=0,failed_calls=0
cmdstat_json.get:calls=20230,usec=539776,usec_per_call=26.68,rejected_calls=0,failed_calls=0
cmdstat_FT.CONFIG:calls=1,usec=53,usec_per_call=53.00,rejected_calls=0,failed_calls=0
cmdstat_json.set:calls=9681,usec=2486650,usec_per_call=256.86,rejected_calls=0,failed_calls=0
cmdstat_json.type:calls=334,usec=4735,usec_per_call=14.18,rejected_calls=0,failed_calls=0
cmdstat_json.objlen:calls=105,usec=1206,usec_per_call=11.49,rejected_calls=0,failed_calls=0
cmdstat_scan:calls=1,usec=602,usec_per_call=602.00,rejected_calls=0,failed_calls=0
cmdstat_ttl:calls=505,usec=291,usec_per_call=0.58,rejected_calls=0,failed_calls=0
cmdstat_get:calls=2,usec=8,usec_per_call=4.00,rejected_calls=0,failed_calls=0
cmdstat_module:calls=1,usec=6,usec_per_call=6.00,rejected_calls=0,failed_calls=0

# Errorstats
errorstat_OFFSET:count=1

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=70888,expires=0,avg_ttl=0

------ CLIENT LIST OUTPUT ------
id=30 addr=172.17.0.1:62708 laddr=172.17.0.2:6379 fd=17 name= age=82 idle=78 flags=P db=0 sub=1 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20504 events=r cmd=subscribe user=default redir=-1
id=15 addr=127.0.0.1:33352 laddr=127.0.0.1:6379 fd=12 name=redisinsight-common-redis-st age=295 idle=100 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20496 events=r cmd=info user=default redir=-1
id=16 addr=127.0.0.1:33354 laddr=127.0.0.1:6379 fd=13 name=redisinsight-browser-764af84b age=294 idle=119 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20512 events=r cmd=json.get user=default redir=-1
id=27 addr=127.0.0.1:33390 laddr=127.0.0.1:6379 fd=14 name=redisinsight-workbench-830929c1 age=100 idle=100 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20520 events=r cmd=FT.CONFIG user=default redir=-1
id=28 addr=172.17.0.1:62706 laddr=172.17.0.2:6379 fd=15 name= age=82 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=97 qbuf-free=40857 argv-mem=44 obl=14 oll=0 omem=0 tot-mem=61548 events=r cmd=FT.SEARCH user=default redir=-1
id=29 addr=172.17.0.1:62704 laddr=172.17.0.2:6379 fd=16 name= age=82 idle=81 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20496 events=r cmd=info user=default redir=-1

------ CURRENT CLIENT INFO ------
id=28 addr=172.17.0.1:62706 laddr=172.17.0.2:6379 fd=15 name= age=82 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=97 qbuf-free=40857 argv-mem=44 obl=14 oll=0 omem=0 tot-mem=61548 events=r cmd=FT.SEARCH user=default redir=-1
argv[0]: 'FT.SEARCH'
argv[1]: 'Security:index'
argv[2]: '*'
argv[3]: 'LIMIT'
argv[4]: '10000'
argv[5]: '100'
argv[6]: 'RETURN'
argv[7]: '0'

------ MODULES INFO OUTPUT ------
# graph_executing commands

# search_version
search_RedisSearch_version:6.2.7

# search_index
search_number_of_indexes:1

# search_fields_statistics
search_fields_tag:Tag=9

# search_runtime_configurations
search_concurrent_mode:OFF
search_enableGC:ON
search_minimal_term_prefix:2
search_maximal_prefix_expansions:200
search_query_timeout_ms:500
search_timeout_policy:return
search_cursor_read_size:1000
search_cursor_max_idle_time:300000
search_max_doc_table_size:1000000
search_max_search_results:1000000
search_max_aggregate_results:10000
search_search_pool_size:20
search_index_pool_size:8
search_gc_scan_size:100
search_min_phonetic_term_length:3

# ReJSON_trace
ReJSON_trace:   0: redis_module::base_info_func
   1: rejson::__info_func
   2: modulesCollectInfo
             at /__w/redis-stack/redis-stack/redis/src/module.c:7100:9
   3: logModulesInfo
             at /__w/redis-stack/redis-stack/redis/src/debug.c:1598:22
   4: printCrashReport
             at /__w/redis-stack/redis-stack/redis/src/debug.c:1849:5
   5: _serverAssert
             at /__w/redis-stack/redis-stack/redis/src/debug.c:907:9
   6: sendChunk
   7: AREQ_Execute
   8: execCommandCommon
   9: RedisModuleCommandDispatcher
             at /__w/redis-stack/redis-stack/redis/src/module.c:695:5
  10: call
             at /__w/redis-stack/redis-stack/redis/src/server.c:3744:5
  11: processCommand
             at /__w/redis-stack/redis-stack/redis/src/server.c:4291:9
  12: processCommandAndResetClient
             at /__w/redis-stack/redis-stack/redis/src/networking.c:2102:9
  13: processInputBuffer
             at /__w/redis-stack/redis-stack/redis/src/networking.c:2203:17
  14: callHandler
             at /__w/redis-stack/redis-stack/redis/src/connhelpers.h:79:18
      connSocketEventHandler
             at /__w/redis-stack/redis-stack/redis/src/connection.c:295:14
  15: aeProcessEvents
             at /__w/redis-stack/redis-stack/redis/src/ae.c:427:17
  16: aeMain
             at /__w/redis-stack/redis-stack/redis/src/ae.c:487:9
  17: main
             at /__w/redis-stack/redis-stack/redis/src/server.c:6456:5
  18: __libc_start_main
  19: _start


------ FAST MEMORY TEST ------
9:M 16 Nov 2022 18:48:58.758 # Bio thread for job type #0 terminated
9:M 16 Nov 2022 18:48:58.758 # Bio thread for job type #1 terminated
9:M 16 Nov 2022 18:48:58.758 # Bio thread for job type #2 terminated
*** Preparing to test memory region 557c72930000 (2281472 bytes)
*** Preparing to test memory region 557c72fb1000 (405504 bytes)
*** Preparing to test memory region 7f6eac000000 (135168 bytes)
*** Preparing to test memory region 7f6eb2800000 (8388608 bytes)
*** Preparing to test memory region 7f6eb3000000 (195035136 bytes)
*** Preparing to test memory region 7f6ebea4a000 (422576128 bytes)
*** Preparing to test memory region 7f6ed7d4b000 (8388608 bytes)
*** Preparing to test memory region 7f6ed854c000 (8388608 bytes)
*** Preparing to test memory region 7f6ed8d4d000 (8388608 bytes)
*** Preparing to test memory region 7f6ed954e000 (8388608 bytes)
*** Preparing to test memory region 7f6ed9f03000 (8388608 bytes)
*** Preparing to test memory region 7f6eda704000 (8388608 bytes)
*** Preparing to test memory region 7f6edb0e3000 (12288 bytes)
*** Preparing to test memory region 7f6edb0e7000 (8388608 bytes)
*** Preparing to test memory region 7f6edb8e8000 (8388608 bytes)
*** Preparing to test memory region 7f6edc0e9000 (8388608 bytes)
*** Preparing to test memory region 7f6edc8ea000 (8388608 bytes)
*** Preparing to test memory region 7f6edd0eb000 (8388608 bytes)
*** Preparing to test memory region 7f6edefa1000 (12288 bytes)
*** Preparing to test memory region 7f6edefa5000 (8388608 bytes)
*** Preparing to test memory region 7f6edf7a6000 (8388608 bytes)
*** Preparing to test memory region 7f6ee03f9000 (28672 bytes)
*** Preparing to test memory region 7f6ee0400000 (8388608 bytes)
*** Preparing to test memory region 7f6ee0ca1000 (4096 bytes)
*** Preparing to test memory region 7f6ee0ce4000 (24576 bytes)
*** Preparing to test memory region 7f6ee0ed8000 (16384 bytes)
*** Preparing to test memory region 7f6ee0efb000 (16384 bytes)
*** Preparing to test memory region 7f6ee11d1000 (16384 bytes)
*** Preparing to test memory region 7f6ee13bd000 (8192 bytes)
*** Preparing to test memory region 7f6ee13f0000 (4096 bytes)
.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O
Fast memory test PASSED, however your memory can still be broken. Please run a memory test for several hours if possible.

=== REDIS BUG REPORT END. Make sure to include from START to END. ===

       Please report the crash by opening an issue on github:

           http://github.com/redis/redis/issues

  Suspect RAM error? Use redis-server --test-memory to verify it.

Aborted
```

### PR DESCRIPTION
**Pull request by MeirShpilraien**
Fix the issue by choosing the correct max results value depends of whether we run a search of aggregate query.

### CODE REVIEW

File: src/aggregate/aggregate_request.c [hunk 1]
```diff
@@ -1034,6 +1034,14 @@ static ResultProcessor *getArrangeRP(AREQ *req, AGGPlan *pln, const PLN_BaseStep
...
   if (!limit) {
     limit = DEFAULT_LIMIT;
+  }
+
+  if ((req->reqflags & QEXEC_F_IS_SEARCH) && RSGlobalConfig.maxSearchResults != UINT64_MAX) {
+    limit = MIN(limit, RSGlobalConfig.maxSearchResults);
+  }
+
+  if (!(req->reqflags & QEXEC_F_IS_SEARCH) && RSGlobalConfig.maxAggregateResults != UINT64_MAX) {
+    limit = MIN(limit, RSGlobalConfig.maxSearchResults);
```
Comment (oshadmi) [inline src/aggregate/aggregate_request.c:1044]:
```suggestion
    limit = MIN(limit, RSGlobalConfig.maxAggregateResults);

```

**Review by oshadmi — APPROVED** [review]
LGTM 👍🏼

**Review by rafie — APPROVED** [review]
