### PR TITLE
explicit error for EXPLAINSCORE w/o WITHSCORES

### LINKED ISSUE #1542: EXPLAINSCORE should not fail silently without WITHSCORES
If you run the EXPLAINSCORE command without also specifying WITHSCORES, you get back no scoring information, nor any errors.

```
localhost:6379> ft.search test "andrew" explainscore
1) (integer) 2
2) "doc:1"
3) 1) "name"
   2) "andrew brookins"
4) "doc:2"
5) 1) "name"
   2) "andrew michael brookins"
```

The command appears to be meaningless without WITHSCORES (but tell me if I'm wrong!). This harms discoverability within the CLI.

We should either tell people the command requires WITHSCORES in order to explain anything, or treat EXPLAINSCORE as implicitly adding WITHSCORES.

### PR DESCRIPTION
**Pull request by ashtul**
fix #1542

### CODE REVIEW

File: src/aggregate/aggregate_request.c [hunk 1]
```diff
@@ -362,6 +362,11 @@ static int parseQueryArgs(ArgsCursor *ac, AREQ *req, RSSearchOptions *searchOpts
     }
   }
 
+  if (req->reqflags & QEXEC_F_SEND_SCOREEXPLAIN && !(req->reqflags & QEXEC_F_SEND_SCORES)) {
```
Comment (rafie) [inline src/aggregate/aggregate_request.c:365]: !!!
`(req->reqflags & QEXEC_F_SEND_SCOREEXPLAIN) && !(req->reqflags & QEXEC_F_SEND_SCORES))`

Comment (ashtul) [reply src/aggregate/aggregate_request.c]: Done

**Review by rafie — APPROVED** [review]
