### PR TITLE
Fix quick exit for heapified union iterator

### LINKED ISSUE #1834: Union iterator with heap always quick exit
The issue arose as part of the fix for #1832

### PR DESCRIPTION
**Pull request by ashtul**
Fixes #1834

### CODE REVIEW

File: src/index.c [hunk 1]
```diff
@@ -81,6 +81,13 @@ static void resetMinIdHeap(UnionIterator *ui) {
                 "count should be equal to number of iterators");
 }
 
+static void UI_HeapAddChildren(void *dst, void *src) {
```
Comment (rafie) [inline src/index.c:84]: Better to:
```
static void UI_HeapAddChildren(UnionIterator *dst, IndexIterator *src) {
```
and cast the function type when passing it somewhere.

**Review by rafie — APPROVED** [review]
