### PR TITLE
[BUG] Field loaded with 'AS' cant be used by funcs

### LINKED ISSUE #2104: FT.AGGREGATE command LOAD option with AS is not working properly
```
> "FT.CREATE" "aggbindex" "SCHEMA" "name" "TEXT" "SORTABLE" "subj1" "NUMERIC" "SORTABLE" "subj2" "NUMERIC" "SORTABLE"
OK
> "FT.ADD" "aggbindex" "data1" "1.0" "FIELDS" "subj2" "70" "name" "abc" "subj1" "20"
OK
> "FT.ADD" "aggbindex" "data2" "1.0" "FIELDS" "subj2" "40" "name" "def" "subj1" "60"
OK
> "FT.AGGREGATE" "aggbindex" "*" "LOAD" "6" "@subj1" "AS" "a" "@subj2" "AS" "b"
1) (integer) 1
2) 1) "a"
   2) "20"
   3) "b"
   4) "70"
3) 1) "a"
   2) "60"
   3) "b"
   4) "40"
> "FT.AGGREGATE" "aggbindex" "*" "LOAD" "6" "@subj1" "AS" "a" "@subj2" "AS" "b" "APPLY" "(@a+@b)/2" "AS" "avg"
(error) Property `a` not loaded in pipeline
```

### PR DESCRIPTION
**Pull request by ashtul**
fixes #2104

### CODE REVIEW

File: src/rlookup.c [hunk 1]
```diff
@@ -70,7 +70,7 @@ RLookupKey *RLookup_GetKeyEx(RLookup *lookup, const char *name, size_t n, int fl
   int isNew = 0;
 
   for (RLookupKey *kk = lookup->head; kk; kk = kk->next) {
-    if (kk->name_len == n && !strncmp(kk->name, name, kk->name_len)) {
+    if (kk->name_len == n && (!strncmp(kk->name, name, kk->name_len) || !strcmp(kk->path, name))) {
```
Comment (rafie) [inline src/rlookup.c:73]: should path always override name?

Comment (oshadmi) [reply src/rlookup.c:73]: Can we avoid the second `strcmp` if `kk->name` and `kk->path` are the same pointer?

Comment (ashtul) [reply src/rlookup.c:73]: @rafie Can you please elaborate?
@oshadmi :+1:

Comment (oshadmi) [reply src/rlookup.c]: Currently we give `name` precedence over `path`, meaning only if `name` does not match, we then try the `path`.
Do we test for ambiguities, since paths may still start with no dot or dollar, so they could match another field name.

Comment (ashtul) [reply src/rlookup.c]: @oshadmi @rafie This function finds a single field against all fields in the lookup table.
There is no precedence here, if either matches, we return the `RLookupKey`.

File: tests/pytests/test_issues.py [hunk 2]
```diff
@@ -169,3 +169,26 @@ def test_issue1988(env):
     env.expect('FT.SEARCH', 'idx', 'foo', 'WITHSCORES').equal([1L, 'doc1', '1', ['t', 'foo']])
     env.expect('FT.SEARCH', 'idx', 'foo', 'SORTBY' , 't').equal([1L, 'doc1', ['t', 'foo']])
     env.expect('FT.SEARCH', 'idx', 'foo', 'WITHSCORES', 'SORTBY' , 't').equal([1L, 'doc1', '1', ['t', 'foo']])
+
+def testIssue2104(env):
```
Comment (oshadmi) [inline tests/pytests/test_issues.py:173]: Should we also add test in test_json.py, with `APPLY`, when name (attribute) and also path (identifier) can be `$.n`, `.n` or `n`?
(with the format `{identifier} [AS {attribute}]`)

**Review by sazzad16 — DISMISSED** [review]

File: src/rlookup.c [hunk 3]
```diff
@@ -365,15 +367,15 @@ static int getKeyCommonHash(const RLookupKey *kk, RLookupRow *dst, RLookupLoadOp
   RSValue *rsv = NULL;
 
   // field name should be translated to a path
```
Comment (oshadmi) [inline src/rlookup.c:369]: Comment could be a bit confusing compared to the following code

**Review by oshadmi — APPROVED** [review]
👍🏼 LGTM (one minor comment)

**Comment by ashtul** [comment]
code and comment change in #2133
