### PR TITLE
Retrieve JSON values w/o getJson 

### LINKED ISSUE #2091: Incorrect TAG tokenization on redismod:edge image
### Overview 
Unexpected behavior when creating a TAG index on JSON RediSearch index. Using the latest redismod:edge image. 
[json_movies.txt](https://github.com/RediSearch/RediSearch/files/6737200/json_movies.txt)

### Steps to re-create issue

1. `FT.CREATE idx:movies ON JSON PREFIX 1 movie: SCHEMA $.title AS title_stem TEXT SORTABLE $.title AS title_no_stem TEXT NOSTEM SORTABLE $.published_at AS published_at NUMERIC SORTABLE $.genre AS genre TAG SEPARATOR ";" SORTABLE`
2. `cat json_movies.txt | redis-cli --pipe`
3. `FT.TAGVALS idx:movies genre`
4. Run some FT.SEARCH queries for TAG fields 
5. Run some FT.SEARCH queries to verify docs are searchable via title or published_at fields

```
127.0.0.1:6379> FT.TAGVALS idx:movies genre
 1) "\"drama"
 2) "\"drama\""
 3) "\"documentary"
 4) "\"comedy"
 5) "\"comedy\""
 6) "\"adventure"
 7) "\"action"
 8) "war\""
 9) "children"
10) "crime"
11) "crime\""
12) "fantasy\""
13) "drama"
14) "drama\""
15) "thriller\""
16) "musical\""
17) "sci-fi\""
127.0.0.1:6379> FT.SEARCH idx:movies "@genre:{action}" LIMIT 0 1
1) (integer) 0
127.0.0.1:6379> FT.SEARCH idx:movies "@genre:{comedy}" LIMIT 0 1
1) (integer) 0
127.0.0.1:6379> FT.SEARCH idx:movies "@genre:{musical}" LIMIT 0 1
1) (integer) 0
127.0.0.1:6379> FT.SEARCH idx:movies "@genre:{drama}" LIMIT 0 1
1) (integer) 1
2) "movie:10"
3) 1) "$"
   2) "{\"title\":\"House of the Rising Sun\",\"genre\":\"Action;Crime;Drama;Thriller\",\"published_at\":1613547265}"
127.0.0.1:6379> FT.SEARCH idx:movies "@genre:{thriller}" LIMIT 0 1
1) (integer) 0
127.0.0.1:6379> FT.SEARCH idx:movies "@genre:{crime}" LIMIT 0 1
1) (integer) 1
2) "movie:10"
3) 1) "$"
   2) "{\"title\":\"House of the Rising Sun\",\"genre\":\"Action;Crime;Drama;Thriller\",\"published_at\":1613547265}"
127.0.0.1:6379> FT.SEARCH idx:movies thrashin
1) (integer) 1
2) "movie:1"
3) 1) "$"
   2) "{\"title\":\"Thrashin\",\"genre\":\"Action;Drama\",\"published_at\":1612778006}"
```

### PR DESCRIPTION
**Pull request by ashtul**
fix #2091

### CODE REVIEW

File: src/rlookup.c [hunk 1]
```diff
@@ -264,6 +264,42 @@ static RSValue *hvalToValue(RedisModuleString *src, RLookupCoerceType type) {
...
+      japi->getDouble(json, &dd);
+      return RS_NumVal(dd);
+    case JSONType_Bool:
+      japi->getBoolean(json, &i);
+      return RS_Int64Val(i);
+    case JSONType_Array:
+    case JSONType_Object:
+      japi->getJSON(json, ctx, &rstr);
+      rs_val = RS_RedisStringVal(rstr);
+      return rs_val;
```
Comment (rafie) [inline src/rlookup.c:295]: `japi->get*` functions can fail, but we don't have a good way to report the error. Still, completely ignoring the return value is problematic.

File: src/rlookup.c [hunk 2]
```diff
@@ -264,6 +264,42 @@ static RSValue *hvalToValue(RedisModuleString *src, RLookupCoerceType type) {
...
 }
 
+static RSValue *jsonValToValue(RedisModuleCtx *ctx, RedisJSON json) {
+  size_t len;
+  char *str;
+  const char *constStr;
+  RedisModuleString *rstr;
+  RSValue *rs_val;
+  long long ll = 0;
+  double dd = 0.0;
```
Comment (rafie) [inline src/rlookup.c:274]: No need to initialize here as we rely on `japi->get*` to either get a value or fail. If we want to initialize nonetheless, we can do it in a block just before `japi->get*`.

File: src/document_basic.c [hunk 3]
```diff
@@ -167,21 +167,21 @@ int Document_LoadSchemaFieldJson(Document *doc, RedisSearchCtx *sctx) {
   doc->score = SchemaRule_JsonScore(sctx->redisCtx, rule, jsonKey, keyName);
   // No payload on JSON as RedisJSON does not support binary fields
 
-  JSONType type;
+  JSONType jsonType;
   doc->fields = rm_calloc(nitems, sizeof(*doc->fields));
```
Comment (rafie) [inline src/document_basic.c:171]: Do we need to check for an existing `doc->fields` (and deallocate it) before assigning a new value here?

**Review by rafie — APPROVED** [review]
