### PR TITLE
Fix Synonym in Chinese

### LINKED ISSUE #2698: Synonym not working with Chinese
When I use Synonym in "language chinese", it won't return the expected docs, and if I use friso to do the synonym it also failes.
I found in src/ext/default.c expandCn  
```
ctx->ExpandTokenWithPhrase(ctx, (const char **)tokVec->data, tokVec->top, token->flags, 1, 0);
```
It does a replace and the token expanded by SynonymExpand loses. 

But in src/tokenize_cn.c cnTokenizer_Next 
```
    switch (tok->type) {
        // Skip words we know we don't care about.
      case __LEX_STOPWORDS__:
      case __LEX_ENPUN_WORDS__:
      case __LEX_CJK_UNITS__:
      case __LEX_NCSYN_WORDS__: // <-here
        continue;

      case __LEX_PUNC_WORDS__:
```
the synonyms added by friso was ignored. 

I tried change replace to 0 in expandCn, synonym in redisearch works again, and if comment out \_\_LEX_NCSYN_WORDS__ in cnTokenizer_Next synonym in friso works.
Is there any particular reason for doing the replace token?

### PR DESCRIPTION
**Pull request by zcw159357**
fixes #2698

### CODE REVIEW

**Comment by ashtul** [comment]
Hi @zcw159357 
Thank you for the PR.
Can you try pushing an empty commit and see if it will now trigger Circle?

**Comment by zcw159357** [comment]
@ashtul Thanks for the tip!

File: src/ext/default.c [hunk 1]
```diff
@@ -350,7 +350,7 @@ static void expandCn(RSQueryExpanderCtx *ctx, RSToken *token) {
     Vector_Push(tokVec, s);
   }
 
-  ctx->ExpandTokenWithPhrase(ctx, (const char **)tokVec->data, tokVec->top, token->flags, 1, 0);
+  ctx->ExpandTokenWithPhrase(ctx, (const char **)tokVec->data, tokVec->top, token->flags, 0, 0);
```
Comment (ashtul) [inline src/ext/default.c:353]: LGTM
Replacing the existing QueryNode removed the synonym node from the union.

**Review by ashtul — APPROVED** [review]
