### PR TITLE
Do not abort GC fork on broken pipe

### LINKED ISSUE #1919: Make sure that Fork does not crash with assert
... when it can not write to the communication pipe

### PR DESCRIPTION
**Pull request by rafie**
Fixes #1919

### CODE REVIEW

File: src/fork_gc.c [hunk 1]
```diff
@@ -84,8 +84,10 @@ static void FGC_sendFixed(ForkGC *fgc, const void *buff, size_t len) {
...
   if (size != len) {
     if (size == -1) {
-      perror("write()");
-      abort();
+      perror("broken pipe, exiting GC fork: write() failed");
+      // just exit, do not abort(), which will trigger a watchdog on RLEC, causing adverse effects
+      RedisModule_Log(NULL, "warning", "GC fork: broken pipe, exiting");
+      exit(1);
     } else {
       RS_LOG_ASSERT(size == len, "buffer failed to write");
```
Comment (MeirShpilraien) [inline src/fork_gc.c:92]: Here also, we need to log and exit

File: src/fork_gc.c [hunk 2]
```diff
@@ -81,14 +81,21 @@ static void FGC_updateStats(RedisSearchCtx *sctx, ForkGC *gc, size_t recordsRemo
...
   RS_LOG_ASSERT(len > 0, "buffer length cannot be 0");
-  ssize_t size = write(fgc->pipefd[GC_WRITERFD], buff, len);
-  if (size != len) {
-    if (size == -1) {
-      perror("write()");
-      abort();
-    } else {
-      RS_LOG_ASSERT(size == len, "buffer failed to write");
+  ssize_t size = 0;
+  while (size < len) {
```
Comment (MeirShpilraien) [inline src/fork_gc.c:85]: I think that the while is not needed, our pipe is in blocking mode, which means that it will block until there is enough space to write all the data. If you get -1 or a size that is less than the size you wrote it means that the pipe is close.

**Review by MeirShpilraien — COMMENTED** [review]
Small comment

**Review by MeirShpilraien — APPROVED** [review]
