### PR TITLE
fix #884, fix wrong results on intersect iterator

### LINKED ISSUE #884: Optional Query weight attribute doesn't work if apply on same field.
Right now, when I try to search a keyword and use an optional query with weight on the same field to boost result, it doesn't seem doing anything.

I have tried redisearch 1.4.0 and 1.4.15

I have indexed document with different TEXT fields of variable sizes and while indexing I have given them different document_score based on my app internal logic. Now I want my users to search for a document by making a query but I want to boost those results that exactly match the query to be at the top.

I have seen scoring algorithm(TF-IDF) sample code provided by redis but none of them seem to do anything with the $weight we provide to a subquery. All of the talks about field weights, document_score and query term frequencies. None of the talks about $weight in a query and how it will effect the end result.

Lets say I have 4 document with different text fields. One of them is `title` field which is also TEXT. The entries of `title` fields of each 4 documents are as follows

"mohsin conversation with the mohsin"
"conversation the conversation - a drama about conversation, the science of conversation."
"Fareham Civilization Church - Sermons and conversations mohsin conversation the"
"mohsin conversation the conversation tahir"
When I generate the following query to redisearch

```@title:(conversation the conversation*) (~@title:"conversation the conversation"=>{$weight: 10;})```
I expect the documents with exact `conversation the conversation` to be at top and all other results (having slop distance > 0) after them.

But the output is totally different. i.e.

"Fareham Civilization Church - Sermons and conversations mohsin conversation the"
 "mohsin conversation with the mohsin"
 "conversation the conversation - a drama about conversation, the science of conversation."
 "mohsin conversation the conversation tahir"

Some Internal info: 
I am using following query to create index:
"FT.create {index_name} STOPWORDS 0 SCHEMA title text weight 50 subtitle text weight 10 author text weight 10 description text weight 20" 

and query to fetch result is as follows:
```@title:(conversation the conversation*) (~@title:"conversation the conversation"=>{$weight: 10;})```

Note: I do see optional query works well if apply on other fields but doesn't seem to work as intended if apply to same field e.g. 

Same field example is as follows but doesn't work:
```@title:(conversation the conversation*) (~@title:"conversation the conversation"=>{$weight: 10;})```

But different field example like  

```@title:(conversation the conversation*) (~@description:"conversation the conversation"=>{$weight: 10;})```

works well

### PR DESCRIPTION
**Pull request by MeirShpilraien**

### CODE REVIEW

File: src/index.c [hunk 1]
```diff
@@ -660,9 +660,17 @@ static int II_SkipTo(void *ctx, t_docId docId, RSIndexResult **hit) {
     // printf("Skipto %d hit @%d\n", docId, ic->current->docId);
 
     // Update the last found id
-    ic->lastFoundId = ic->base.current->docId;
-    if (hit) *hit = ic->base.current;
-    return INDEXREAD_OK;
+    if (ic->maxSlop >= 0) {
```
Comment (mnunberg) [inline src/index.c]: Eliminate duplication. Something like:
```
int haveMatch = 0;
if (slop > = 0) {
  if (IsWithinRange(...)) {
    haveMatch = 1;
  }
} else {
  haveMatch = 1;
}
if (haveMatch) {
  ic->lastFoundId = ..
  if (hit) ..
}
```

Comment (mnunberg) [reply src/index.c]: Or even better...
```
if (nfound == ic->num && (slop == -1 || IsWithinRange(...))) {
  ...
```
