### PR TITLE
Fix for Issue1018 for 1.4

### LINKED ISSUE #1018: RediSearch 'highlight' function causes segfault (v1.4.19)
Hi,

I am using redis v5.0.7 with redisearch  v1.4.19, the latter build from source, and I am consistently experiencing the following issue:

1) Executing search queries that use the 'highlight' functionality may cause redis to come crashing to a halt with a segfault.
2) Some search queries that use the 'highlight' functionality do not cause a segfault and if such a query does not cause a segfault, that query will never cause a segfault.
3) Some search queries that use the 'highlight' functionality do cause a segfault and if such a query does cause a segfault, that query will always cause a segfault.
4) A query that does not use  'highlight' will never cause a segfault.

Examples:

1) ft.search 'r:g' 'soccer' withscores limit 0 50 highlight fields 3 name localName aliases
Result: never causes a segfault

2) ft.search 'r:g' 'soccer field' withscores limit 0 50 highlight fields 3 name localName aliases
Result: always causes a segfault

3)  ft.search 'r:g' ''soccer field' withscores limit 0 50 
Result: never causes a segfault

4) ft.search 'r:g' 'koekange' withscores limit 0 50 highlight fields 3 name localName aliases
Result: always causes a segfault

5) ft.search 'r:g' 'koekange' withscores limit 0 50
Result: never causes a segfault

Attached is the redis bug report and the ft.info output. If there is anything else you may need, please let me know.

Regards,

Edwin

---

=== REDIS BUG REPORT START: Cut & paste starting from here ===
30936:M 18 Dec 2019 11:34:53.639 # Redis 5.0.7 crashed by signal: 11
30936:M 18 Dec 2019 11:34:53.640 # Crashed running the instruction at: 0x7f8c85166e3d
30936:M 18 Dec 2019 11:34:53.640 # Accessing address: 0x7f8c6937fffd
30936:M 18 Dec 2019 11:34:53.641 # Failed assertion: <no assertion failed> (<no file>:0)

------ STACK TRACE ------
EIP:
/lib/x86_64-linux-gnu/libc.so.6(+0x18ee3d)[0x7f8c85166e3d]

Backtrace:
/usr/bin/redis-server 127.0.0.1:6379(logStackTrace+0x5a)[0x55e6542c367a]
/usr/bin/redis-server 127.0.0.1:6379(sigsegvHandler+0xb1)[0x55e6542c3e31]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12890)[0x7f8c853db890]
/lib/x86_64-linux-gnu/libc.so.6(+0x18ee3d)[0x7f8c85166e3d]
/usr/lib/redis/modules/redisearch.so(FragmentList_HighlightWholeDocS+0xb5)[0x7f8c7c608ad5]
/usr/lib/redis/modules/redisearch.so(+0x51228)[0x7f8c7c60a228]
/usr/lib/redis/modules/redisearch.so(+0x513ca)[0x7f8c7c60a3ca]
/usr/lib/redis/modules/redisearch.so(QueryPlan_Run+0xe2)[0x7f8c7c61b0f2]
/usr/lib/redis/modules/redisearch.so(_SearchCommand+0x13e)[0x7f8c7c6112be]
/usr/lib/redis/modules/redisearch.so(+0x4236d)[0x7f8c7c5fb36d]
/usr/lib/redis/modules/redisearch.so(+0xb4abe)[0x7f8c7c66dabe]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76db)[0x7f8c853d06db]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7f8c850f988f]

ft.info r:g
 1) index_name
 2) r:g
 3) index_options
 4) (empty list or set)
 5) fields
 6)  1) 1) dbId
        2) type
        3) TAG
        4) SEPARATOR
        5) ,
     2) 1) name
        2) type
        3) TEXT
        4) WEIGHT
        5) "1"
     3) 1) localName
        2) type
        3) TEXT
        4) WEIGHT
        5) "1"
     4) 1) aliases
        2) type
        3) TEXT
        4) WEIGHT
        5) "1"
     5) 1) countryName
        2) type
        3) TEXT
        4) WEIGHT
        5) "0.5"
     6) 1) stateName
        2) type
        3) TEXT
        4) WEIGHT
        5) "1"
     7) 1) flags
        2) type
        3) TEXT
        4) WEIGHT
        5) "1"
        6) NOINDEX
     8) 1) lastModificationDate
        2) type
        3) TEXT
        4) WEIGHT
        5) "1"
        6) NOINDEX
     9) 1) originalName
        2) type
        3) TEXT
        4) WEIGHT
        5) "1"
        6) NOINDEX
    10) 1) originalLocalName
        2) type
        3) TEXT
        4) WEIGHT
        5) "1"
        6) NOINDEX
    11) 1) originalAliases
        2) type
        3) TEXT
        4) WEIGHT
        5) "1"
        6) NOINDEX
    12) 1) formattedAddress
        2) type
        3) TEXT
        4) WEIGHT
        5) "1"
        6) NOINDEX
    13) 1) geoLocation
        2) type
        3) GEO
    14) 1) countryCode
        2) type
        3) TAG
        4) SEPARATOR
        5) ,
    15) 1) stateCode
        2) type
        3) TAG
        4) SEPARATOR
        5) ,
    16) 1) dataAvailability
        2) type
        3) TAG
        4) SEPARATOR
        5) ,
    17) 1) status
        2) type
        3) TAG
        4) SEPARATOR
        5) ,
    18) 1) permanentlyClosed
        2) type
        3) TAG
        4) SEPARATOR
        5) ,
 7) num_docs
 8) "32608"
 9) max_doc_id
10) "32608"
11) num_terms
12) "28364"
13) num_records
14) "412012"
15) inverted_sz_mb
16) "1.4447908401489258"
17) total_inverted_index_blocks
18) "65309"
19) offset_vectors_sz_mb
20) "0.20822525024414062"
21) doc_table_size_mb
22) "4.011566162109375"
23) sortable_values_size_mb
24) "0"
25) key_table_size_mb
26) "1.924159049987793"
27) records_per_doc_avg
28) "12.635304219823356"
29) bytes_per_record_avg
30) "3.6770118346067591"
31) offsets_per_term_avg
32) "0.52993602128093353"
33) offset_bits_per_record_avg
34) "8"
35) gc_stats
36)  1) bytes_collected
     2) "0"
     3) total_ms_run
     4) "422"
     5) total_cycles
     6) "4"
     7) avarage_cycle_time_ms
     8) "105.5"
     9) last_run_time_ms
    10) "91"
    11) gc_numeric_trees_missed
    12) "0"
    13) gc_blocks_denied
    14) "0"
37) cursor_stats
38) 1) global_idle
    2) (integer) 0
    3) global_total
    4) (integer) 0
    5) index_capacity
    6) (integer) 128
    7) index_total
    8) (integer) 0

### PR DESCRIPTION
**Pull request by ashtul**
Fixes #1018 
This PR fixes 2 issues:
- NONINDEX fields caused crashes
- Empty fields caused crashes

### CODE REVIEW

File: src/document.c [hunk 1]
```diff
@@ -393,8 +393,8 @@ FIELD_PREPROCESSOR(fulltextPreprocessor) {
     uint32_t newTokPos;
     while (0 != (newTokPos = aCtx->tokenizer->Next(aCtx->tokenizer, &tok))) {
       forwardIndexTokenFunc(&tokCtx, &tok);
-      lastTokPos = newTokPos;
     }
+    lastTokPos = aCtx->tokenizer->ctx.lastOffset;
```
Comment (MeirShpilraien) [inline src/document.c]: :+1:

File: src/document.c [hunk 2]
```diff
@@ -366,7 +366,7 @@ FIELD_PREPROCESSOR(fulltextPreprocessor) {
     RSSortingVector_Put(aCtx->sv, fs->sortIdx, (void *)c, RS_SORTABLE_STR);
   }
 
-  if (FieldSpec_IsIndexable(fs)) {
+  if (FieldSpec_IsIndexable(fs) && *c != '\0') {
```
Comment (MeirShpilraien) [inline src/document.c]: Do you still need the `*c != '\0'`?

Comment (ashtul) [reply src/document.c]: Thought to leave as an optimization but since very unlikely, removed it
